FactoryGirl.define do
  factory :summary do
    name "MyString"
    number "MyString"
    ic "MyString"
    management_organization "MyString"
    start_date "2019-07-24 15:06:35"
    size "MyString"
    percent_complete "MyString"
    incident_type "MyString"
    cause "MyString"
    suppression_strategy "MyString"
    complexity "MyString"
    report_date "2019-07-24 15:06:35"
    prepared_by "MyString"
    approved_by "MyString"
    primary_agency "MyString"
    state "MyString"
    county "MyString"
    city "MyString"
    jurisdiction "MyString"
    ownership "MyString"
    latitude "9.99"
    longitude "9.99"
    area_description "MyString"
    fire_behavior "MyText"
    narrative "MyText"
    fuel_type "MyText"
    damage_assessment "MyText"
    injuries "MyString"
    threat_remark "MyText"
    weather "MyText"
    projected_spread_12 "MyText"
    projected_spread_24 "MyText"
    projected_spread_48 "MyText"
    projected_spread_72 "MyText"
    projected_spread_after "MyText"
    stragetic_objectives "MyText"
    threat_12 "MyText"
    threat_24 "MyText"
    threat_48 "MyText"
    threat_72 "MyText"
    threat_after "MyText"
    critical_needs_12 "MyText"
    critical_needs_24 "MyText"
    critical_needs_48 "MyText"
    critical_needs_72 "MyText"
    critical_needs_after "MyText"
    strategic_discussion "MyText"
    tomorrows_plan "MyText"
    anticipated_completion "2019-07-24"
    cost "9.99"
    remarks "MyText"
    resources "MyText"
    cooperators "MyText"
  end
end
